version: '3.8'

services:
    db:
        image: mysql:8.0.33-debian
        container_name: nc3_db
        restart: unless-stopped
        command: --default-authentication-plugin=mysql_native_password
        env_file:
            - docker-compose.env
        environment:
                MYSQL_DATABASE: ${DB_DATABASE}
                MYSQL_USER: ${DB_USERNAME}
                MYSQL_PASSWORD: ${DB_PASSWORD}
                MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - dbdata:/var/lib/mysql
            - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - app_network
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                HTTP_PROXY: http://proxy.lc1.conostix.com:3128
                HTTPS_PROXY: http://proxy.lc1.conostix.com:3128
                http_proxy: http://proxy.lc1.conostix.com:3128
                https_proxy: http://proxy.lc1.conostix.com:3128
        container_name: nc3_app
        ports:
            - "127.0.0.1:9000:9000"
        restart: unless-stopped
        env_file:
            - docker-compose.env
        environment:
            DB_HOST: db
        volumes:
            - storage_data:/var/www/html/storage
            - ./public:/var/www/html/public
        depends_on:
            - db
        networks:
            - app_network

networks:
    app_network:
        driver: bridge

volumes:
    dbdata:
    storage_data:
