version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: nc3_app
        restart: unless-stopped
        environment:
            DB_HOST: db
            DB_DATABASE: nc3_db
            DB_USERNAME: nc3_user
            DB_PASSWORD: nc3_password
        volumes:
            - ./:/var/www/html
            - ./storage:/var/www/html/storage
        depends_on:
            - db
        networks:
            - app_network

    nginx:
        image: nginx:stable-alpine
        container_name: nc3_nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - app
        networks:
            - app_network

    db:
        image: mysql:8.0
        container_name: nc3_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: nc3_db
            MYSQL_USER: nc3_user
            MYSQL_PASSWORD: nc3_password
            MYSQL_ROOT_PASSWORD: nc3_root_password
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - app_network

    backup:
        build:
            context: .
            dockerfile: Dockerfile.backup
        container_name: nc3_backup
        environment:
            DB_HOST: db
            DB_DATABASE: nc3_db
            DB_USERNAME: nc3_user
            DB_PASSWORD: nc3_password
        volumes:
            - ./:/var/www/html
            - /home/ppa:/backups
            - dbdata:/var/lib/mysql:ro
        depends_on:
            - db
        networks:
            - app_network

networks:
    app_network:
        driver: bridge

volumes:
    dbdata:
        driver: local
