# .github/workflows/deploy.yml
name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Ensure directory exists and set permissions
            mkdir -p /var/www/applications.nc3.lu
            cd /var/www/applications.nc3.lu

            # If this is first deployment, initialize git
            if [ ! -d .git ]; then
              git init
              git remote add origin ${{ github.server_url }}/${{ github.repository }}.git
              git fetch
            fi

            # Update code
            git fetch --all
            git checkout -f master
            git pull origin master



            # Create production .env file
            cat > .env << EOL
            APP_NAME="NC3's Application Platform"
            APP_ENV=production
            APP_KEY=${{ secrets.APP_KEY }}
            APP_DEBUG=false
            APP_TIMEZONE=UTC
            APP_URL=https://applications.nc3.lu

            APP_LOCALE=en
            APP_FALLBACK_LOCALE=en
            APP_FAKER_LOCALE=en_US

            APP_MAINTENANCE_DRIVER=file

            BCRYPT_ROUNDS=12

            LOG_CHANNEL=stack
            LOG_STACK=single
            LOG_DEPRECATIONS_CHANNEL=null
            LOG_LEVEL=debug

            DB_CONNECTION=mysql
            DB_HOST=db
            DB_PORT=3306
            DB_DATABASE=nc3_db
            DB_USERNAME=nc3_user
            DB_PASSWORD=nc3_password

            SESSION_DRIVER=database
            SESSION_LIFETIME=120
            SESSION_ENCRYPT=false
            SESSION_PATH=/
            SESSION_DOMAIN=null

            BROADCAST_CONNECTION=log
            FILESYSTEM_DISK=local
            QUEUE_CONNECTION=database

            CACHE_STORE=database
            CACHE_PREFIX=

            MAIL_MAILER=log
            MAIL_HOST=mail.mbox.lu
            MAIL_PORT=2525
            MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}
            MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}
            MAIL_ENCRYPTION=null
            MAIL_FROM_ADDRESS=app@nc3.lu
            MAIL_FROM_NAME="NC3's Application Platform"

            VITE_APP_NAME="NC3's Application Platform"
            EOL

            cd submission_platform
            # Start/update containers
            docker-compose down # Ensure clean state
            docker-compose up -d --build # Build and start everything

            # Run deployment script
            ./scripts/deploy.sh
