name: Deploy to Production

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test SSH Connection
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          debug: true
          script: |
            echo "SSH connection successful"


      - name: Build Assets
        run: |
          npm ci
          npm run build
          zip -r build_artifacts.zip public/build

      - name: Sync Files to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: 22
          source: "."
          target: "/var/www/applications.nc3.lu"
          rm: true


      - name: Upload Build Artifacts
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          source: "build_artifacts.zip"
          target: "/var/www/applications.nc3.lu/"

      - name: Create .env File on Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cat > /var/www/applications.nc3.lu/.env << EOL
            APP_NAME="NC3's Application Platform"
            APP_ENV=production
            APP_KEY=${{ secrets.APP_KEY }}
            APP_DEBUG=false
            APP_URL=https://applications.nc3.lu
            APP_LOCALE=en
            APP_FALLBACK_LOCALE=en
            APP_FAKER_LOCALE=en_US

            APP_MAINTENANCE_DRIVER=file

            BCRYPT_ROUNDS=12

            LOG_CHANNEL=stack
            LOG_STACK=single
            LOG_DEPRECATIONS_CHANNEL=null
            LOG_LEVEL=debug

            DB_CONNECTION=mysql
            DB_HOST=db
            DB_PORT=3306
            DB_DATABASE=${{ secrets.DB_DATABASE }}
            DB_USERNAME=${{ secrets.DB_USERNAME }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}

            SESSION_DRIVER=database
            SESSION_LIFETIME=120
            SESSION_ENCRYPT=false
            SESSION_PATH=/
            SESSION_DOMAIN=null

            BROADCAST_CONNECTION=log
            FILESYSTEM_DISK=local
            QUEUE_CONNECTION=database

            CACHE_STORE=database
            CACHE_PREFIX=

            MAIL_MAILER=log
            MAIL_HOST=mail.mbox.lu
            MAIL_PORT=2525
            MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}
            MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}
            MAIL_ENCRYPTION=null
            MAIL_FROM_ADDRESS=app@nc3.lu
            MAIL_FROM_NAME="NC3's Application Platform"

            VITE_APP_NAME="NC3's Application Platform"
            EOL
            chmod 600 /var/www/applications.nc3.lu/.env

      - name: Create Docker Compose .env File on Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cat > /var/www/applications.nc3.lu/docker-compose.env << EOL
            DB_DATABASE=${{ secrets.DB_DATABASE }}
            DB_USERNAME=${{ secrets.DB_USERNAME }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
            EOL
            chmod 600 /var/www/applications.nc3.lu/docker-compose.env
      - name: Run Deployment Script on Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            cd /var/www/applications.nc3.lu
            unzip -o build_artifacts.zip -d public
            chmod +x scripts/deploy.sh
            ./scripts/deploy.sh
